from __future__ import annotations

import json
from types import SimpleNamespace

import pytest
import torch
from safetensors.torch import save_file

from freetoken.models.deepseek_v41.engram import (
    EngramHasher,
    EngramLayout,
    EngramShardPlan,
    build_compressed_token_map,
    compute_engram_hash_ids,
    compute_hash_multipliers,
    load_engram_host_table,
)


def _layout() -> EngramLayout:
    return EngramLayout.build(
        layer_ids=(1, 14),
        num_embeddings=(384_006_168, 384_016_682),
        max_ngram_size=4,
        n_heads=8,
        head_dim=256,
        vocab_size=16_000_000,
    )


def test_official_layout_exactly_fills_both_tables():
    layout = _layout()
    assert layout.hashes_per_token == 24
    assert [sum(p for group in layer for p in group) for layer in layout.primes] == [
        384_006_168,
        384_016_682,
    ]
    assert layout.primes[0][0] == (
        16_000_057,
        16_000_079,
        16_000_081,
        16_000_097,
        16_000_121,
        16_000_129,
        16_000_133,
        16_000_183,
    )


def test_hash_fixture_matches_official_reference():
    """Fixture generated by the checkpoint's inference/engram.py, not this module."""

    layout = _layout()
    token_map = torch.arange(128, dtype=torch.int64)
    multipliers = compute_hash_multipliers(layout.layer_ids, 4, 99_092)
    assert multipliers.tolist() == [
        [76_632_096_046_245, 4_839_876_093_313, 35_959_672_319_349, 73_987_337_458_391],
        [67_716_810_739_261, 51_510_806_800_915, 30_921_347_202_721, 82_619_226_485_591],
    ]
    flat = [[p for group in layer for p in group] for layer in layout.primes]
    offsets = torch.tensor([[sum(row[:i]) for i in range(len(row))] for row in flat])
    tokens = torch.tensor([[99, 42, 10, 3]], dtype=torch.int64)
    got = compute_engram_hash_ids(
        tokens,
        torch.zeros_like(tokens, dtype=torch.bool),
        pad_id=2,
        token_map=token_map,
        multipliers=multipliers,
        primes=torch.tensor(layout.primes),
        offsets=offsets,
    )
    assert got.tolist() == [[
        [
            8_220_142, 24_076_129, 42_973_604, 50_161_011, 68_969_938, 80_580_362,
            102_387_095, 127_047_346, 128_178_040, 155_599_543, 172_362_639,
            188_430_535, 193_087_801, 211_429_563, 238_958_298, 249_716_007,
            271_400_830, 280_018_239, 289_357_450, 318_030_951, 331_814_380,
            344_491_158, 355_493_385, 378_679_135,
        ],
        [
            11_523_440, 21_938_014, 44_040_595, 58_778_561, 66_148_416, 92_452_634,
            110_886_980, 120_121_793, 137_160_488, 148_833_347, 160_914_255,
            184_264_145, 201_990_816, 211_078_389, 226_251_914, 252_651_771,
            257_112_609, 275_732_145, 295_556_258, 317_769_611, 335_227_198,
            340_560_456, 363_970_592, 369_017_439,
        ],
    ]]


class _Backend:
    def __init__(self, decoded: list[str], raw: list[str]):
        self.decoded = decoded
        self.raw = raw

    def decode(self, ids, skip_special_tokens=False):
        return self.decoded[ids[0]]

    def id_to_token(self, token_id):
        return self.raw[token_id]


class _Tokenizer:
    def __init__(self, decoded: list[str], raw: list[str]):
        self.backend_tokenizer = _Backend(decoded, raw)
        self._size = len(decoded)

    def __len__(self):
        return self._size


def test_compressed_token_map_normalizes_case_space_accents_and_raw_bytes():
    tok = _Tokenizer(
        ["The", " the ", "THE", "café", "CAFE", " ", "", "\ufffd", "\ufffd"],
        ["The", "Ġthe", "THE", "café", "CAFE", "Ġ", "", "<0xC2>", "<0xA0>"],
    )
    lookup, size = build_compressed_token_map(tok)
    assert lookup[0] == lookup[1] == lookup[2]
    assert lookup[3] == lookup[4]
    assert lookup[5] != lookup[6]
    assert lookup[7] != lookup[8]
    assert size == 6


def test_ragged_hash_windows_match_one_shot_across_chunk_boundary():
    layout = _layout()
    hasher = object.__new__(EngramHasher)
    hasher.layout = layout
    hasher.pad_id = 2
    hasher.token_map = torch.arange(256, dtype=torch.int64)
    hasher.multipliers = compute_hash_multipliers(layout.layer_ids, 4, 99_092)
    flat = [[p for group in layer for p in group] for layer in layout.primes]
    hasher.primes = torch.tensor(layout.primes)
    hasher.offsets = torch.tensor([[sum(row[:i]) for i in range(len(row))] for row in flat])

    sequence = torch.tensor([3, 10, 42, 99, 7, 8], dtype=torch.int64)
    full = hasher.row_ids(
        sequence,
        torch.arange(sequence.numel()),
        torch.tensor([0, sequence.numel()]),
        torch.tensor([[2, 2, 2]]),
    )
    tail = hasher.row_ids(
        sequence[4:],
        torch.arange(4, 6),
        torch.tensor([0, 2]),
        sequence[1:4].view(1, 3),
    )
    assert torch.equal(tail, full[4:])


@pytest.mark.skipif(not torch.cuda.is_available(), reason="needs CUDA")
def test_cuda_graph_hasher_follows_token_position_and_history_inputs():
    """Every decode-time Engram input must remain dynamic across graph replays."""
    layout = _layout()
    hasher = object.__new__(EngramHasher)
    hasher.layout = layout
    hasher.pad_id = 2
    hasher.token_map = torch.arange(256, dtype=torch.int64)
    hasher.multipliers = compute_hash_multipliers(layout.layer_ids, 4, 99_092)
    flat = [[p for group in layer for p in group] for layer in layout.primes]
    hasher.primes = torch.tensor(layout.primes)
    hasher.offsets = torch.tensor(
        [[sum(row[:i]) for i in range(len(row))] for row in flat]
    )
    hasher.to("cuda")

    input_ids = torch.tensor([99], device="cuda", dtype=torch.int64)
    positions = torch.tensor([3], device="cuda", dtype=torch.int64)
    cu = torch.tensor([0, 1], device="cuda", dtype=torch.int32)
    history = torch.tensor([[3, 10, 42]], device="cuda", dtype=torch.int64)
    # Warm every operation before capture, just as GraphRunner does.
    hasher.row_ids(input_ids, positions, cu, history)
    captured = torch.empty((1, len(layout.layer_ids), layout.hashes_per_token),
                           device="cuda", dtype=torch.int64)
    graph = torch.cuda.CUDAGraph()
    with torch.cuda.graph(graph):
        captured.copy_(hasher.row_ids(input_ids, positions, cu, history))

    cases = [
        (7, 4, [10, 42, 99]),
        (23, 1, [2, 2, 7]),
    ]
    for token, position, prefix in cases:
        input_ids.fill_(token)
        positions.fill_(position)
        history.copy_(torch.tensor([prefix], device="cuda"))
        want = hasher.row_ids(input_ids, positions, cu, history).clone()
        graph.replay()
        assert torch.equal(captured, want)


def test_ep2_shard_plan_is_exact_and_nonoverlapping():
    plans = [EngramShardPlan.build(384_006_168, 256, rank=r, world_size=2) for r in range(2)]
    assert plans[0].row_start == 0
    assert plans[0].row_end == plans[1].row_start
    assert plans[1].row_end == 384_006_168
    assert sum(p.rows for p in plans) == 384_006_168
    assert sum(p.nbytes for p in plans) == 384_006_168 * (256 + 8)


def _regular_reader(buf, path, *, file_offset, nbytes, dest_offset=0, **_):
    with open(path, "rb") as handle:
        handle.seek(file_offset)
        data = handle.read(nbytes)
    assert len(data) == nbytes
    memoryview(buf).cast("B")[dest_offset : dest_offset + nbytes] = data
    return nbytes


def test_loader_reads_only_the_owned_rows(tmp_path):
    rows, dim, layer = 11, 32, 1
    weight = (torch.arange(rows * dim, dtype=torch.float32).reshape(rows, dim) % 13).to(
        torch.float8_e4m3fn
    )
    scale_u8 = (torch.arange(rows, dtype=torch.uint8).reshape(rows, 1) + 123).contiguous()
    scale = scale_u8.view(torch.float8_e8m0fnu)
    shard = tmp_path / "model-00001-of-00001.safetensors"
    save_file(
        {
            f"layers.{layer}.engram.embed.weight": weight,
            f"layers.{layer}.engram.embed.scale": scale,
        },
        shard,
    )
    index = {
        "metadata": {"total_size": shard.stat().st_size},
        "weight_map": {
            f"layers.{layer}.engram.embed.weight": shard.name,
            f"layers.{layer}.engram.embed.scale": shard.name,
        },
    }
    (tmp_path / "model.safetensors.index.json").write_text(json.dumps(index))

    table = load_engram_host_table(
        str(tmp_path),
        layer_id=layer,
        num_embeddings=rows,
        dim=dim,
        rank=1,
        world_size=2,
        pin=False,
        collapse=False,
        reader=_regular_reader,
    )
    assert table.plan.row_start == 5
    assert torch.equal(table.weight.view(torch.uint8), weight[5:].view(torch.uint8))
    assert torch.equal(table.scale.view(torch.uint8), scale[5:].view(torch.uint8))
